PostAp/config/routes.rb
Community::Application.routes.draw do

resources :posts

get 'dashboard' => 'home#index'
get 'register' =>'registration#register'

root :to => 'home#index'

devise_for :members, :controllers => { :registrations =>'registration'}
devise_scope :member do
  get '/members/sign_out' => 'devise/sessions#destroy'
end
 
end

PostAp/app/models/contact.rb
class Contact < ActiveRecord::Base

  belongs_to :member
  
end

PostAp/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
 # attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  has_one :contact
end

PostAp/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :member
end

PostAp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  protect_from_forgery
end

PostAp/app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
   @contact = Contact.new
  end
end

PostAp/app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index
    
    @posts = Post.all
    @member = Member.all
  end
end

PostAp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.member_id = current_member.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :url, :createdat, :content)
    end
end

PostAp/app/controllers/registration_controller.rb
class RegistrationController < Devise::RegistrationsController

def user_params
      params.require(:member).permit(:username, :email, :password, :password_confirmation, :remember_me)

    end

def new
    #super
    @member= Member.new
    @contact = Contact.new
  end

  def create

    @member = Member.new
    @member.username = params[:member][:username]
    @member.email = params[:member][:email]
    @member.password = params[:member][:password]
    @member.password_confirmation =params[:member][:password_confirmation]
    
    @contact = Contact.new
    @contact.mobile = params[:contact][:mobile]
    @contact.address = params[:contact][:address]
    @member.valid?


    if @member.errors.blank?

     @member.save 
     @contact.member = @member
     @contact.save
     
      flash[:notice] = "created"
      redirect_to dashboard_path
    else
     render :action => "new"
    end
    end
     
end

 

PostAp/app/helpers/application_helper.rb
module ApplicationHelper
end

PostAp/app/helpers/contact_helper.rb
module ContactHelper
end

PostAp/app/helpers/home_helper.rb
module HomeHelper
end

PostAp/app/helpers/posts_helper.rb
module PostsHelper
end

PostAp/app/helpers/registration_helper.rb
module RegistrationHelper
end

PostAp/app/views/home/index.html.erb
<body class="wrapper" >
  <br>
<% if member_signed_in? %>


  <h3>you have succesfully signed in</h3>
  <br>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr class="row header green">
      <th class="cell" >Name</th>
      <th class="cell">Title</th>
      <th class="cell">Url</th>
      <th class="cell">Createdat</th>
      <th class="cell">Content</th>
      <th class="cell">Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class="row">
        <td class="cell"><%= post.name %></td>
        <td class="cell"><%= post.title %></td>
        <td class="cell"><%= post.url %></td>
        <td class="cell"><%= post.createdat %></td>
        <td class="cell"><%= post.content %></td>
        <td class="cell"><%= post.member.email %></td>
        <td class="cell"><%= link_to 'Show', post %></td>
        <% if current_member.email == post.member.email %>
          <td class="cell"><%= link_to 'Edit', edit_post_path(post) %></td>
          <td class="cell"><%= link_to 'Destroy', post, method: :destroy, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>




  <%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
  

<% else %>

  
<h1>Post Application </h1>
April 25 1, 2018	Akshay Paliwal
<div class="CL"></div>

<p>
Sign up as a new user 
</p>
<p>
Once signed up log into the application, you would be redirected to the Dashboard where you should be able to play around with posts present there .
</p>

<% end %>
</body>

PostAp/app/views/layouts/_footer.erb
<div class="FOOTER">
	<center><h5 style="color:white ;margin: 5px 0px;">Akshay Paliwal/h5></center>
</div>

PostAp/app/views/layouts/_header.erb
<div class="HEADER">
	<center><h1 style="color:#990000;margin: 5px 0px;">Application to manage Post's</h2></center>
	<br>
	<div class="SHELL">
		<div class="FLOAT_LEFT">
			<%= link_to "Home", root_path %>
	    </div>
		<div class="FLOAT_RIGHT">
		<% if current_member %>
			Welcome <b style="color: #38761d;"><%= current_member.username || current_member.email %></b>&nbsp;|&nbsp;
			<%= link_to "Sign Out", destroy_member_session_path, :method=>:delete %>
		<% else %>
			<%= link_to "Sign In", new_member_session_path(current_member) %>&nbsp;|&nbsp;
			<%= link_to "Register", new_member_registration_path(current_member) %>
		<% end %>
		</div>
	</div>
</div>

PostAp/app/views/layouts/_notice.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

PostAp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title>Community</title>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= render :partial=>"/layouts/header" %>
	
	<div class="SHELL">
		<%= render :partial=>"/layouts/notice" %>
		<div class="CL"></div>
		<%= yield %>
		<div class="CL"></div>
	</div>
	
	<%= render :partial=>"/layouts/footer" %>


</body>
</html>

PostAp/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :createdat %><br>
    <%= f.date_select :createdat %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PostAp/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

PostAp/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Url</th>
      <th>Createdat</th>
      <th>Content</th>
      <th>Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.createdat %></td>
        <td><%= post.content %></td>
        <td><%= post.member.username %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= button_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

PostAp/app/views/posts/new.html.erb
<<body class="wrapper" >
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

</body>

PostAp/app/views/posts/show.html.erb
<body class="wrapper" >
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<p>
  <strong>Createdat:</strong>
  <%= @post.createdat %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Member:</strong>
  <%= @post.member %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>
</body>